package org.banking.model;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class Transaction {

    private int transactionId; // Optional, auto-generated by DB
    private String accountNumber;
    private String transactionType;
    private BigDecimal amount;
    private Timestamp timestamp;
    private String description;

    // Constructor
    public Transaction(String accountNumber, String transactionType, BigDecimal amount, Timestamp timestamp, String description) {
        this.accountNumber = accountNumber;
        this.transactionType = transactionType;
        this.amount = amount;
        this.timestamp = timestamp;
        this.description = description;
    }

    // Default constructor for DAO retrieval
    public Transaction() {}

    // Getters & Setters
    public int getTransactionId() { return transactionId; }
    public void setTransactionId(int transactionId) { this.transactionId = transactionId; }

    public String getAccountNumber() { return accountNumber; }
    public void setAccountNumber(String accountNumber) { this.accountNumber = accountNumber; }

    public String getTransactionType() { return transactionType; }
    public void setTransactionType(String transactionType) { this.transactionType = transactionType; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    public Timestamp getTimestamp() { return timestamp; }
    public void setTimestamp(Timestamp timestamp) { this.timestamp = timestamp; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
}
